spring:
  application:
    name: cms-service-zuul
server:
  port: 8082
  eureka-server: localhost
  eureka-auth-name: admin
  eureka-auth-pwd: 123
eureka:
  client:
    service-url:
      defaultZone: http://${server.eureka-auth-name}:${server.eureka-auth-pwd}@${server.eureka-server}:8761/eureka
  instance:
    hostname: ${spring.application.name}
zuul:
  routes:
    api:
      path: /api/**
      serviceId: cms-service
    api_a:
      path: /api_a/**
      url: http://localhost:8081/