spring:
  application:
    name: cms-service
eureka:
  client:
    service-url:
      defaultZone: http://${server.eureka-auth-name}:${server.eureka-auth-pwd}@${server.eureka-server}:8761/eureka
  instance:
    hostname: ${spring.application.name}
    health-check-url-path: http://${server.eureka-server}:${server.port}/checkhealth
    status-page-url-path: http://${server.eureka-server}:${server.port}/status
server:
  eureka-server: localhost
  eureka-auth-name: admin
  eureka-auth-pwd: 123
  port: 8081